### ISSUE TITLE
可以给一个ipv6的版本吗？谢谢

### ISSUE THREAD

**Issue by lkunxyz** [MisterChangRay/custom-tcp-filter#1]

**Comment by MisterChangRay** [comment]
最近很忙没时间做，以后空了考虑增加。

**Comment by lkunxyz** [comment]
按照格式模仿写了一个ipv6的版本：

`
unsigned int sdp_spa_mangle_hook_v6(void *priv,
			       struct sk_buff *skb,
			       const struct nf_hook_state *state)
{
    struct ipv6hdr *iph6;  
    struct udphdr *udph;    
    struct tcphdr  *tcph = NULL;
    unsigned int udp_len;
    char *d, *d1;

    uint16_t idx = 0, found = 0, i = 0;
    int hdr_len, datalen, ohdr_len, option_len;
    char myskbuff[256] = {0};
    char pskbuff[256] = {0};
  
    int off_option = 0, off_head = 0, newoption_len = 0;
    unsigned char newoption[128] = {0};

    //return NF_ACCEPT;
    
    /* 获取IPv6首部指针 */
    iph6 = ipv6_hdr(skb);
    if (!iph6)
        return NF_ACCEPT;

    /* 过滤 ::/128 空类型地址 */
    if (ipv6_addr_any(&iph6->saddr) || ipv6_addr_any(&iph6->daddr))
        return NF_ACCEPT;

    /* 过滤源地址和目的地址相等的报文 */
    if (ipv6_addr_equal(&iph6->saddr, &iph6->daddr))
        return NF_ACCEPT;

    /* 过滤环回地址报文 ::1/128 */
    if (ipv6_addr_loopback(&iph6->saddr) || ipv6_addr_loopback(&iph6->daddr))        
        return NF_ACCEPT;

    /* 只处理UDP报文 */    
    if (iph6->nexthdr != NEXTHDR_TCP)
    {
        printk("protocol:%d\n", iph6->nexthdr);
        return NF_ACCEPT;
    }
        
    /* 设置传输层首部 */
    tcph = (struct tcphdr *)skb_transport_header(skb);
    if (!tcph) {
        printk("sdp iph or tcph is NULL.\n");
        return NF_ACCEPT;
    }

    printk("skb_headroom(skb):%d\n", skb_headroom(skb));
    if (skb_headroom(skb) < 22) {
        printk("sdp head room is not enough\n"); 
        return NF_ACCEPT;
    }

    if (!(skb->data[0] ^ 0x3c)) { 
        printk("sdp thisn't IPv6 packet. %x\n", skb->data[0]);
        return NF_ACCEPT;
    }

    printk("sdp sdp_spa_mangle_hook_v6 src:%pI6  sport:%d, dst:%pI6 dport:%d\n", &iph6->saddr, ntohs(tcph->source), &iph6->daddr, ntohs(tcph->dest));
  
    /* New logic */
    hdr_len = 40 + (tcph->doff) * 4;            // 源包头长: ip header + tcp header
    off_option = 40 + 5*4;                       //ip header(ipv6头部固定40) + tcp 部分header（tcp头部到option (5*4)）
    option_len = hdr_len - off_option;
    memcpy(myskbuff, skb->data, off_option);
    sdp_mangle_tcp_option(tcph->seq, skb->data + off_option, option_len, newoption, &newoption_len);
    memcpy(myskbuff + off_option, newoption, newoption_len);
    off_head = newoption_len - option_len; // 头部变化 
    printk("hdr_len:%d tcph->doff:%d  option_len:%d  newoption_len:%d  off_head:%d, total:%d", hdr_len, tcph->doff, option_len, newoption_len, off_head, (skb->len)); 

    printk("sdp before generate new skb.\n");
    skb_pull(skb, hdr_len);              // 移出原头
    skb_push(skb, hdr_len + off_head);   // 为新头腾出空间
    memcpy(skb->data, myskbuff, hdr_len + off_head);  // 添加新头
    printk("sdp update header offset in skb hdr_len:%d off_head:%d, theader:%d, nheader:%d\n", hdr_len, off_head, skb->transport_header, skb->network_header);
  
    skb->transport_header = skb->transport_header - off_head;  
    skb->network_header = skb->network_header - off_head;
    printk("sdp update header offset in skb off_head:%d, theader:%d, nheader:%d\n", off_head, skb->transport_header, skb->network_header);
   

    iph6 = ipv6_hdr(skb);
    tcph = (struct tcphdr *)skb_transport_header(skb);         // 更新 tcp 头指针指 tcp 指向新头
    tcph->doff = 5 + newoption_len/4; // 更新 TCP 头部偏移量 (1 = 4 Bytes)

    tcph->check = 0;
    skb->csum = csum_partial(skb_transport_header(skb), ntohs(tcph->doff * 4), 0);
    tcph->check = csum_ipv6_magic(&iph6->saddr, &iph6->daddr, ntohs(tcph->doff * 4), IPPROTO_TCP, skb->csum);        
    skb->ip_summed = CHECKSUM_NONE;

    /* 如果首部校验和为0，替换成CSUM_MANGLED_0 */
    if (0 == tcph->check)
        tcph->check = CSUM_MANGLED_0;


    //tcph->check = csum_ipv6_magic(&iph6->saddr, &iph6->daddr, tcph->doff << 2, IPPROTO_TCP, csum_partial((char *)tcph, tcph->doff << 2, skb->csum));
    //tcph->check = csum_ipv6_magic(&iph6->saddr, &iph6->daddr, (20 + newoption_len) , IPPROTO_TCP, 0); 
    //the reason is not clear, but without it, it seems the hardware will re-calcuate the checksum
    //skb->ip_summed = CHECKSUM_UNNECESSARY; 

    printk("sdp new src:%pI6  sport:%d, dst:%pI6 dport:%d\n", &iph6->saddr, ntohs(tcph->source), &iph6->daddr, ntohs(tcph->dest));
    printk("sdp new tcp_checksum = %x  tcph->doff=%d  newoption_len:%d total:%d\n", tcph->check, tcph->doff, newoption_len, htons(skb->len));
    return NF_ACCEPT;
}
`

我模仿ipv4,danshi总是出现问题：
![image](https://user-images.githubusercontent.com/3108757/169760158-dd09459c-f1f9-49d7-89c8-60cf36090552.png)
